</section>
<!--============================================ Content Wrapper Section End ======================================================= -->
<!-- ------------------------------------------------------------------------------------------------------------------------------- -->


<!-- =========================================== Footer Start ===================================================================== -->
<footer class="main-footer">
  <strong>
    <p class="mb-0">© 2021 IIC MSIT Website | Designd By Technical Team | IIC MSIT</a></p>
  </strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 1.0.0
  </div>
</footer>
<!-- ============================================================= Footer End ================================================================= --->
<!-- ------------------------------------------------------------------------------------------------------------------------------- -->



<!-- ================================================== Admin Sidebar Start =============================================================== -->
<aside class="control-sidebar control-sidebar-dark">
  <!--=================== Generated by Scripts============== -->
</aside>
<!-- ================================================== Admin Sidebar End =============================================================== -->
<!-- ------------------------------------------------------------------------------------------------------------------------------- -->



<!-- ============================================================ Scripts ========================================================== -->

<!-- jQuery -->
<script src="assets/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 4 -->
<script src="assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="assets/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="assets/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="assets/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="assets/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="assets/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="assets/plugins/moment/moment.min.js"></script>
<script src="assets/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="assets/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="assets/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="assets/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="assets/js/dashboard.js"></script>
<script src="assets/js/slick.js"></script>
<!-- ============================================================== -->
<script src="assets/js/adminajax.js?v=<?php echo time(); ?>"></script>

<!-- ------------------------------------------------------------------------------------------------------------------------------- -->
<!-- ==================================================== body end ================================================================= -->
</body>

</html>
</body>

</html>